apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-manager
  template:
    metadata:
      labels:
        app: book-manager
    spec:
      containers:
        - image: asusnik12354/book-manager-service:master
          name: book-info-retrieval 
          ports:
            - containerPort: 5001
              name: server

---
apiVersion: v1
kind: Service
metadata:
  name: book-manager
spec:
  type: ClusterIP
  ports:
    - port: 5001
      protocol: TCP
      targetPort: server
  selector:
    app: book-manager
