apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-info-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-info
  template:
    metadata:
      labels:
        app: book-info
    spec:
      containers:
        - image: asusnik12354/book-info-retrieval-service:master
          imagePullPolicy: Always
          name: book-info-retrieval 
          ports:
            - containerPort: 5000
              name: server
---
apiVersion: v1
kind: Service
metadata:
  name: book-info
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      targetPort: server
  selector:
    app: book-info
