apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-manager 
  template:
    metadata:
      labels:
        app: book-manager 
    spec:
      containers:
        - image: asusnik12354/book-info-retrieval-service:master
          name: book-info-retrieval 
          ports:
            - containerPort: 5000
              name: server

---
apiVersion: v1
kind: Service
metadata:
  name: book-manager 
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: server
  selector:
    app: book-manager
