apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-register-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-register
  template:
    metadata:
      labels:
        app: login-register
    spec:
      containers:
        - image: asusnik12354/login-register-service:master
          imagePullPolicy: Always
          name: login-register 
          ports:
            - containerPort: 5002
              name: server
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: ETCD_HOST
              value: etcd.ingress-nginx.svc.cluster.local
            - name: ETCD_PORT
              value: "2379"

---
apiVersion: v1
kind: Service
metadata:
  name: login-register
spec:
  type: ClusterIP
  ports:
    - port: 5002
      protocol: TCP
      targetPort: server
  selector:
    app: login-register
